### ISSUE TITLE
update to debian buster

### ISSUE THREAD

**Issue by niklasf** [niklasf/build-raspbian-image#11]
1. Update the distribution https://github.com/niklasf/build-raspbian-image/blob/master/bootstrap.sh#L7
2. Update the package sources: https://github.com/niklasf/build-raspbian-image/blob/master/etc/apt/sources.list
3. Build image and test on a real device

**Comment by singhanadcheamontha** [comment]
> 1. Update the distribution https://github.com/niklasf/build-raspbian-image/blob/master/bootstrap.sh#L7
> 2. Update the package sources: https://github.com/niklasf/build-raspbian-image/blob/master/etc/apt/sources.list
> 3. Build image and test on a real device
