### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ezar** [niklasf/build-raspbian-image#3]
Can you help me?

> Enabling systemd-networkd for DHCP
> EEEK! Something bad happened...
> [Errno 2] No such file or directory: '/tmp/tmpL4A7zr/etc/systemd/network/99-dhcp.network'
> Cleaning up
> ERROR: [Errno 2] No such file or directory: '/tmp/tmpL4A7zr/etc/systemd/network/99-dhcp.network'

**Comment by niklasf** [comment]
Looks like Raspbian changed a bit. You could try to remove the line with `--enable-dhcp` from `bootstraph.sh`.

At the moment I am too far away from my Raspberry to test if anything else is required for network setup.
