### ISSUE TITLE
Are the kernel headers available somewhere?

### ISSUE THREAD

**Issue by zoof** [niklasf/build-raspbian-image#8]
The rtl8192cu module is unreliable so I need to compile the proprietary module.

**Comment by niklasf** [comment]
You need something other than the `linux-headers-...` packages?

**Comment by zoof** [comment]
They don't match the installed kernel version.  Should I install the repo kernel and headers?

**Comment by niklasf** [comment]
Mhh, that sucks. The problem was also raised with rpi-update (which this script uses to install the kernel). Not quite satisfactory, but mentions a possible solution: https://github.com/Hexxeh/rpi-update/issues/55

**Comment by zoof** [comment]
Thanks much -- that worked.  But apparently the built-in kernel module is supposed to work fine so I guess I'm not giving the pi enough power.
